// Code generated by protoc-gen-go.
// source: proto/game.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	proto/game.proto

It has these top-level messages:
	Game
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Game_FrameType int32

const (
	Game_Message Game_FrameType = 0
	Game_Kick    Game_FrameType = 1
	Game_Ping    Game_FrameType = 2
)

var Game_FrameType_name = map[int32]string{
	0: "Message",
	1: "Kick",
	2: "Ping",
}
var Game_FrameType_value = map[string]int32{
	"Message": 0,
	"Kick":    1,
	"Ping":    2,
}

func (x Game_FrameType) String() string {
	return proto1.EnumName(Game_FrameType_name, int32(x))
}
func (Game_FrameType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Game struct {
}

func (m *Game) Reset()                    { *m = Game{} }
func (m *Game) String() string            { return proto1.CompactTextString(m) }
func (*Game) ProtoMessage()               {}
func (*Game) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Game_Frame struct {
	Type    Game_FrameType `protobuf:"varint,1,opt,name=Type,enum=proto.Game_FrameType" json:"Type,omitempty"`
	Message []byte         `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (m *Game_Frame) Reset()                    { *m = Game_Frame{} }
func (m *Game_Frame) String() string            { return proto1.CompactTextString(m) }
func (*Game_Frame) ProtoMessage()               {}
func (*Game_Frame) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Game_Frame) GetType() Game_FrameType {
	if m != nil {
		return m.Type
	}
	return Game_Message
}

func (m *Game_Frame) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto1.RegisterType((*Game)(nil), "proto.Game")
	proto1.RegisterType((*Game_Frame)(nil), "proto.Game.Frame")
	proto1.RegisterEnum("proto.Game_FrameType", Game_FrameType_name, Game_FrameType_value)
}

func init() { proto1.RegisterFile("proto/game.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x4f, 0xcc, 0x4d, 0xd5, 0x03, 0x33, 0x85, 0x58, 0xc1, 0x94, 0x52, 0x13, 0x23,
	0x17, 0x8b, 0x7b, 0x62, 0x6e, 0xaa, 0x94, 0x0f, 0x17, 0xab, 0x5b, 0x51, 0x62, 0x6e, 0xaa, 0x90,
	0x26, 0x17, 0x4b, 0x48, 0x65, 0x41, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x9f, 0x91, 0x28, 0x44,
	0xb9, 0x1e, 0x48, 0x8d, 0x1e, 0x58, 0x01, 0x48, 0x32, 0x08, 0xac, 0x44, 0x48, 0x82, 0x8b, 0xdd,
	0x37, 0xb5, 0xb8, 0x38, 0x31, 0x3d, 0x55, 0x82, 0x49, 0x81, 0x51, 0x83, 0x27, 0x08, 0xc6, 0x55,
	0xd2, 0xe1, 0xe2, 0x84, 0x2b, 0x16, 0xe2, 0x86, 0x2b, 0x13, 0x60, 0x10, 0xe2, 0xe0, 0x62, 0xf1,
	0xce, 0x4c, 0xce, 0x16, 0x60, 0x04, 0xb1, 0x02, 0x32, 0xf3, 0xd2, 0x05, 0x98, 0x92, 0xd8, 0xc0,
	0x76, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd5, 0x4e, 0x56, 0xb1, 0xa6, 0x00, 0x00, 0x00,
}
