// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	agent.proto

It has these top-level messages:
	Agent
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Agent_StatusCode int32

const (
	Agent_STATUS_OK        Agent_StatusCode = 0
	Agent_STATUS_NOT_FOUND Agent_StatusCode = 1
)

var Agent_StatusCode_name = map[int32]string{
	0: "STATUS_OK",
	1: "STATUS_NOT_FOUND",
}
var Agent_StatusCode_value = map[string]int32{
	"STATUS_OK":        0,
	"STATUS_NOT_FOUND": 1,
}

func (x Agent_StatusCode) String() string {
	return proto1.EnumName(Agent_StatusCode_name, int32(x))
}
func (Agent_StatusCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Agent struct {
}

func (m *Agent) Reset()                    { *m = Agent{} }
func (m *Agent) String() string            { return proto1.CompactTextString(m) }
func (*Agent) ProtoMessage()               {}
func (*Agent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Agent_Result struct {
	Status Agent_StatusCode `protobuf:"varint,1,opt,name=status,enum=proto.Agent_StatusCode" json:"status"`
	Msg    string           `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *Agent_Result) Reset()                    { *m = Agent_Result{} }
func (m *Agent_Result) String() string            { return proto1.CompactTextString(m) }
func (*Agent_Result) ProtoMessage()               {}
func (*Agent_Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Agent_Result) GetStatus() Agent_StatusCode {
	if m != nil {
		return m.Status
	}
	return Agent_STATUS_OK
}

func (m *Agent_Result) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Agent_UserEntry struct {
	Usn uint64 `protobuf:"fixed64,1,opt,name=usn" json:"usn,omitempty"`
}

func (m *Agent_UserEntry) Reset()                    { *m = Agent_UserEntry{} }
func (m *Agent_UserEntry) String() string            { return proto1.CompactTextString(m) }
func (*Agent_UserEntry) ProtoMessage()               {}
func (*Agent_UserEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *Agent_UserEntry) GetUsn() uint64 {
	if m != nil {
		return m.Usn
	}
	return 0
}

func init() {
	proto1.RegisterType((*Agent)(nil), "proto.Agent")
	proto1.RegisterType((*Agent_Result)(nil), "proto.Agent.Result")
	proto1.RegisterType((*Agent_UserEntry)(nil), "proto.Agent.UserEntry")
	proto1.RegisterEnum("proto.Agent_StatusCode", Agent_StatusCode_name, Agent_StatusCode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AgentService service

type AgentServiceClient interface {
	// kick user
	KickUser(ctx context.Context, in *Agent_UserEntry, opts ...grpc.CallOption) (*Agent_Result, error)
}

type agentServiceClient struct {
	cc *grpc.ClientConn
}

func NewAgentServiceClient(cc *grpc.ClientConn) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) KickUser(ctx context.Context, in *Agent_UserEntry, opts ...grpc.CallOption) (*Agent_Result, error) {
	out := new(Agent_Result)
	err := grpc.Invoke(ctx, "/proto.AgentService/KickUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AgentService service

type AgentServiceServer interface {
	// kick user
	KickUser(context.Context, *Agent_UserEntry) (*Agent_Result, error)
}

func RegisterAgentServiceServer(s *grpc.Server, srv AgentServiceServer) {
	s.RegisterService(&_AgentService_serviceDesc, srv)
}

func _AgentService_KickUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Agent_UserEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).KickUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AgentService/KickUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).KickUser(ctx, req.(*Agent_UserEntry))
	}
	return interceptor(ctx, in, info, handler)
}

var _AgentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "KickUser",
			Handler:    _AgentService_KickUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}

func init() { proto1.RegisterFile("agent.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x4c, 0x4f, 0xcd,
	0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xcb, 0x18, 0xb9, 0x58,
	0x1d, 0x41, 0xc2, 0x52, 0xde, 0x5c, 0x6c, 0x41, 0xa9, 0xc5, 0xa5, 0x39, 0x25, 0x42, 0xfa, 0x5c,
	0x6c, 0xc5, 0x25, 0x89, 0x25, 0xa5, 0xc5, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x7c, 0x46, 0xe2, 0x10,
	0x2d, 0x7a, 0x60, 0x75, 0x7a, 0xc1, 0x60, 0x29, 0xe7, 0xfc, 0x94, 0xd4, 0x20, 0xa8, 0x32, 0x21,
	0x01, 0x2e, 0xe6, 0xdc, 0xe2, 0x74, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x10, 0x53, 0x4a,
	0x96, 0x8b, 0x33, 0xb4, 0x38, 0xb5, 0xc8, 0x35, 0xaf, 0xa4, 0xa8, 0x12, 0x24, 0x5d, 0x5a, 0x9c,
	0x07, 0x36, 0x8c, 0x2d, 0x08, 0xc4, 0x54, 0x32, 0xe4, 0xe2, 0x42, 0x18, 0x23, 0xc4, 0xcb, 0xc5,
	0x19, 0x1c, 0xe2, 0x18, 0x12, 0x1a, 0x1c, 0xef, 0xef, 0x2d, 0xc0, 0x20, 0x24, 0xc2, 0x25, 0x00,
	0xe5, 0xfa, 0xf9, 0x87, 0xc4, 0xbb, 0xf9, 0x87, 0xfa, 0xb9, 0x08, 0x30, 0x1a, 0xb9, 0x73, 0xf1,
	0x80, 0xed, 0x0f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x15, 0x32, 0xe7, 0xe2, 0xf0, 0xce, 0x4c,
	0xce, 0x06, 0xd9, 0x22, 0x24, 0x86, 0xe2, 0x40, 0xb8, 0xc5, 0x52, 0xc2, 0x28, 0xe2, 0x10, 0xdf,
	0x25, 0xb1, 0x81, 0xc5, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0d, 0x26, 0xcc, 0x60, 0x0e,
	0x01, 0x00, 0x00,
}
