// Code generated by protoc-gen-go.
// source: common.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	common.proto

It has these top-level messages:
	RspHeader
	UserBasicInfo
	C2SGetSeedReq
	S2CGetSeedRsp
	C2SLoginReq
	S2CLoginRsp
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// commands
// S -> C : even
// C -> S : odd
type Cmd int32

const (
	Cmd_RESERVED       Cmd = 0
	Cmd_HEART_BEAT_REQ Cmd = 1
	Cmd_HEART_BEAT_RSP Cmd = 2
	Cmd_LOGIN_REQ      Cmd = 17
	Cmd_LOGIN_RSP      Cmd = 18
	Cmd_GET_SEED_REQ   Cmd = 49
	Cmd_GET_SEED_RSP   Cmd = 50
	Cmd_PING_REQ       Cmd = 4097
	Cmd_PING_RSP       Cmd = 4098
	Cmd_CMD_COMMON_END Cmd = 65536
)

var Cmd_name = map[int32]string{
	0:     "RESERVED",
	1:     "HEART_BEAT_REQ",
	2:     "HEART_BEAT_RSP",
	17:    "LOGIN_REQ",
	18:    "LOGIN_RSP",
	49:    "GET_SEED_REQ",
	50:    "GET_SEED_RSP",
	4097:  "PING_REQ",
	4098:  "PING_RSP",
	65536: "CMD_COMMON_END",
}
var Cmd_value = map[string]int32{
	"RESERVED":       0,
	"HEART_BEAT_REQ": 1,
	"HEART_BEAT_RSP": 2,
	"LOGIN_REQ":      17,
	"LOGIN_RSP":      18,
	"GET_SEED_REQ":   49,
	"GET_SEED_RSP":   50,
	"PING_REQ":       4097,
	"PING_RSP":       4098,
	"CMD_COMMON_END": 65536,
}

func (x Cmd) String() string {
	return proto.EnumName(Cmd_name, int32(x))
}
func (Cmd) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ResultCode int32

const (
	ResultCode_RESULT_OK             ResultCode = 0
	ResultCode_RESULT_TIMEOUT        ResultCode = 1
	ResultCode_RESULT_UNAUTH         ResultCode = 2
	ResultCode_RESULT_UNKNOWN_CMD    ResultCode = 3
	ResultCode_RESULT_INVALID        ResultCode = 4
	ResultCode_RESULT_INTERNAL_ERROR ResultCode = 5
)

var ResultCode_name = map[int32]string{
	0: "RESULT_OK",
	1: "RESULT_TIMEOUT",
	2: "RESULT_UNAUTH",
	3: "RESULT_UNKNOWN_CMD",
	4: "RESULT_INVALID",
	5: "RESULT_INTERNAL_ERROR",
}
var ResultCode_value = map[string]int32{
	"RESULT_OK":             0,
	"RESULT_TIMEOUT":        1,
	"RESULT_UNAUTH":         2,
	"RESULT_UNKNOWN_CMD":    3,
	"RESULT_INVALID":        4,
	"RESULT_INTERNAL_ERROR": 5,
}

func (x ResultCode) String() string {
	return proto.EnumName(ResultCode_name, int32(x))
}
func (ResultCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Gender int32

const (
	Gender_GENDER_UNKNOWN Gender = 0
	Gender_GENDER_FEMALE  Gender = 1
	Gender_GENDER_MALE    Gender = 2
)

var Gender_name = map[int32]string{
	0: "GENDER_UNKNOWN",
	1: "GENDER_FEMALE",
	2: "GENDER_MALE",
}
var Gender_value = map[string]int32{
	"GENDER_UNKNOWN": 0,
	"GENDER_FEMALE":  1,
	"GENDER_MALE":    2,
}

func (x Gender) String() string {
	return proto.EnumName(Gender_name, int32(x))
}
func (Gender) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type RspHeader struct {
	Status    ResultCode `protobuf:"varint,1,opt,name=status,enum=proto.common.ResultCode" json:"status,omitempty"`
	Timestamp uint64     `protobuf:"fixed64,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Msg       string     `protobuf:"bytes,3,opt,name=msg" json:"msg,omitempty"`
}

func (m *RspHeader) Reset()                    { *m = RspHeader{} }
func (m *RspHeader) String() string            { return proto.CompactTextString(m) }
func (*RspHeader) ProtoMessage()               {}
func (*RspHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RspHeader) GetStatus() ResultCode {
	if m != nil {
		return m.Status
	}
	return ResultCode_RESULT_OK
}

func (m *RspHeader) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *RspHeader) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type UserBasicInfo struct {
	Usn      uint64 `protobuf:"fixed64,1,opt,name=usn" json:"usn,omitempty"`
	Uid      uint64 `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	Birthday uint64 `protobuf:"fixed64,3,opt,name=birthday" json:"birthday,omitempty"`
	Gender   Gender `protobuf:"varint,4,opt,name=gender,enum=proto.common.Gender" json:"gender,omitempty"`
	Nickname string `protobuf:"bytes,5,opt,name=nickname" json:"nickname,omitempty"`
	Email    string `protobuf:"bytes,6,opt,name=email" json:"email,omitempty"`
	Avatar   string `protobuf:"bytes,7,opt,name=avatar" json:"avatar,omitempty"`
	Country  string `protobuf:"bytes,8,opt,name=country" json:"country,omitempty"`
}

func (m *UserBasicInfo) Reset()                    { *m = UserBasicInfo{} }
func (m *UserBasicInfo) String() string            { return proto.CompactTextString(m) }
func (*UserBasicInfo) ProtoMessage()               {}
func (*UserBasicInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserBasicInfo) GetUsn() uint64 {
	if m != nil {
		return m.Usn
	}
	return 0
}

func (m *UserBasicInfo) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UserBasicInfo) GetBirthday() uint64 {
	if m != nil {
		return m.Birthday
	}
	return 0
}

func (m *UserBasicInfo) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_GENDER_UNKNOWN
}

func (m *UserBasicInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserBasicInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserBasicInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserBasicInfo) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

type C2SGetSeedReq struct {
	SendSeed []byte `protobuf:"bytes,1,opt,name=send_seed,json=sendSeed,proto3" json:"send_seed,omitempty"`
	RecvSeed []byte `protobuf:"bytes,2,opt,name=recv_seed,json=recvSeed,proto3" json:"recv_seed,omitempty"`
}

func (m *C2SGetSeedReq) Reset()                    { *m = C2SGetSeedReq{} }
func (m *C2SGetSeedReq) String() string            { return proto.CompactTextString(m) }
func (*C2SGetSeedReq) ProtoMessage()               {}
func (*C2SGetSeedReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *C2SGetSeedReq) GetSendSeed() []byte {
	if m != nil {
		return m.SendSeed
	}
	return nil
}

func (m *C2SGetSeedReq) GetRecvSeed() []byte {
	if m != nil {
		return m.RecvSeed
	}
	return nil
}

type S2CGetSeedRsp struct {
	Header   *RspHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	SendSeed []byte     `protobuf:"bytes,2,opt,name=send_seed,json=sendSeed,proto3" json:"send_seed,omitempty"`
	RecvSeed []byte     `protobuf:"bytes,3,opt,name=recv_seed,json=recvSeed,proto3" json:"recv_seed,omitempty"`
}

func (m *S2CGetSeedRsp) Reset()                    { *m = S2CGetSeedRsp{} }
func (m *S2CGetSeedRsp) String() string            { return proto.CompactTextString(m) }
func (*S2CGetSeedRsp) ProtoMessage()               {}
func (*S2CGetSeedRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *S2CGetSeedRsp) GetHeader() *RspHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *S2CGetSeedRsp) GetSendSeed() []byte {
	if m != nil {
		return m.SendSeed
	}
	return nil
}

func (m *S2CGetSeedRsp) GetRecvSeed() []byte {
	if m != nil {
		return m.RecvSeed
	}
	return nil
}

type C2SLoginReq struct {
	Timestamp uint64 `protobuf:"fixed64,1,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *C2SLoginReq) Reset()                    { *m = C2SLoginReq{} }
func (m *C2SLoginReq) String() string            { return proto.CompactTextString(m) }
func (*C2SLoginReq) ProtoMessage()               {}
func (*C2SLoginReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *C2SLoginReq) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type S2CLoginRsp struct {
	Header   *RspHeader     `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	UserInfo *UserBasicInfo `protobuf:"bytes,2,opt,name=user_info,json=userInfo" json:"user_info,omitempty"`
}

func (m *S2CLoginRsp) Reset()                    { *m = S2CLoginRsp{} }
func (m *S2CLoginRsp) String() string            { return proto.CompactTextString(m) }
func (*S2CLoginRsp) ProtoMessage()               {}
func (*S2CLoginRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *S2CLoginRsp) GetHeader() *RspHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *S2CLoginRsp) GetUserInfo() *UserBasicInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*RspHeader)(nil), "proto.common.RspHeader")
	proto.RegisterType((*UserBasicInfo)(nil), "proto.common.UserBasicInfo")
	proto.RegisterType((*C2SGetSeedReq)(nil), "proto.common.C2SGetSeedReq")
	proto.RegisterType((*S2CGetSeedRsp)(nil), "proto.common.S2CGetSeedRsp")
	proto.RegisterType((*C2SLoginReq)(nil), "proto.common.C2SLoginReq")
	proto.RegisterType((*S2CLoginRsp)(nil), "proto.common.S2CLoginRsp")
	proto.RegisterEnum("proto.common.Cmd", Cmd_name, Cmd_value)
	proto.RegisterEnum("proto.common.ResultCode", ResultCode_name, ResultCode_value)
	proto.RegisterEnum("proto.common.Gender", Gender_name, Gender_value)
}

func init() { proto.RegisterFile("common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 633 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xc1, 0x6e, 0xd3, 0x4a,
	0x14, 0x86, 0x6b, 0x27, 0x75, 0x93, 0x93, 0xa4, 0x77, 0x3a, 0xea, 0xed, 0xf5, 0xa5, 0x2c, 0xa2,
	0xac, 0xaa, 0x82, 0x02, 0x98, 0x0d, 0x4b, 0x52, 0x7b, 0x48, 0xad, 0x26, 0x76, 0x18, 0x3b, 0x45,
	0x62, 0x63, 0xb9, 0xf1, 0xb4, 0xb5, 0xa8, 0xed, 0xe0, 0x71, 0x2a, 0xca, 0xaa, 0xb0, 0xe3, 0x71,
	0x78, 0x24, 0xde, 0x04, 0xcd, 0xd8, 0x49, 0x9b, 0x2c, 0x58, 0xb0, 0xca, 0xfc, 0xdf, 0xff, 0xcf,
	0x39, 0xc7, 0x3a, 0x19, 0x68, 0xcf, 0xb2, 0x24, 0xc9, 0xd2, 0xfe, 0x3c, 0xcf, 0x8a, 0x0c, 0xb7,
	0xe5, 0x4f, 0xbf, 0x64, 0xbd, 0x04, 0x9a, 0x94, 0xcf, 0x4f, 0x59, 0x18, 0xb1, 0x1c, 0xbf, 0x04,
	0x8d, 0x17, 0x61, 0xb1, 0xe0, 0xba, 0xd2, 0x55, 0x8e, 0x76, 0x0d, 0xbd, 0xff, 0x38, 0xdb, 0xa7,
	0x8c, 0x2f, 0x6e, 0x0a, 0x33, 0x8b, 0x18, 0xad, 0x72, 0xf8, 0x29, 0x34, 0x8b, 0x38, 0x61, 0xbc,
	0x08, 0x93, 0xb9, 0xae, 0x76, 0x95, 0x23, 0x8d, 0x3e, 0x00, 0x8c, 0xa0, 0x96, 0xf0, 0x2b, 0xbd,
	0xd6, 0x55, 0x8e, 0x9a, 0x54, 0x1c, 0x7b, 0xbf, 0x14, 0xe8, 0x4c, 0x39, 0xcb, 0x4f, 0x42, 0x1e,
	0xcf, 0xec, 0xf4, 0x32, 0x13, 0x99, 0x05, 0x4f, 0x65, 0x43, 0x8d, 0x8a, 0xa3, 0x24, 0x71, 0x24,
	0xab, 0xd5, 0xa9, 0x38, 0xe2, 0x27, 0xd0, 0xb8, 0x88, 0xf3, 0xe2, 0x3a, 0x0a, 0xef, 0x64, 0x31,
	0x8d, 0xae, 0x34, 0x7e, 0x0e, 0xda, 0x15, 0x4b, 0x23, 0x96, 0xeb, 0x75, 0x39, 0xf3, 0xfe, 0xfa,
	0xcc, 0x43, 0xe9, 0xd1, 0x2a, 0x23, 0x2a, 0xa5, 0xf1, 0xec, 0x53, 0x1a, 0x26, 0x4c, 0xdf, 0x96,
	0x63, 0xad, 0x34, 0xde, 0x87, 0x6d, 0x96, 0x84, 0xf1, 0x8d, 0xae, 0x49, 0xa3, 0x14, 0xf8, 0x00,
	0xb4, 0xf0, 0x36, 0x2c, 0xc2, 0x5c, 0xdf, 0x91, 0xb8, 0x52, 0x58, 0x87, 0x9d, 0x59, 0xb6, 0x48,
	0x8b, 0xfc, 0x4e, 0x6f, 0x48, 0x63, 0x29, 0x7b, 0x36, 0x74, 0x4c, 0xc3, 0x1b, 0xb2, 0xc2, 0x63,
	0x2c, 0xa2, 0xec, 0x33, 0x3e, 0x84, 0x26, 0x67, 0x69, 0x14, 0x70, 0xc6, 0x22, 0xf9, 0xa1, 0x6d,
	0xda, 0x10, 0x40, 0xf8, 0xc2, 0xcc, 0xd9, 0xec, 0xb6, 0x34, 0xd5, 0xd2, 0x14, 0x40, 0x98, 0xbd,
	0xaf, 0xd0, 0xf1, 0x0c, 0x73, 0x59, 0x8a, 0xcf, 0xf1, 0x0b, 0xd0, 0xae, 0xe5, 0xae, 0x64, 0x9d,
	0x96, 0xf1, 0xdf, 0xc6, 0x86, 0x96, 0xab, 0xa4, 0x55, 0x6c, 0xbd, 0xb7, 0xfa, 0xa7, 0xde, 0xb5,
	0x8d, 0xde, 0xcf, 0xa0, 0x65, 0x1a, 0xde, 0x28, 0xbb, 0x8a, 0x53, 0xf1, 0x11, 0x6b, 0x9b, 0x56,
	0x36, 0x36, 0xdd, 0xfb, 0x02, 0x2d, 0xcf, 0x30, 0xcb, 0xf0, 0xdf, 0x8c, 0xf9, 0x06, 0x9a, 0x0b,
	0xce, 0xf2, 0x20, 0x4e, 0x2f, 0x33, 0x39, 0x66, 0xcb, 0x38, 0x5c, 0xbf, 0xb3, 0xf6, 0xaf, 0xa1,
	0x0d, 0x91, 0x16, 0xa7, 0xe3, 0x9f, 0x0a, 0xd4, 0xcc, 0x24, 0xc2, 0x6d, 0x68, 0x50, 0xe2, 0x11,
	0x7a, 0x4e, 0x2c, 0xb4, 0x85, 0x31, 0xec, 0x9e, 0x92, 0x01, 0xf5, 0x83, 0x13, 0x32, 0xf0, 0x03,
	0x4a, 0xde, 0x23, 0x65, 0x93, 0x79, 0x13, 0xa4, 0xe2, 0x0e, 0x34, 0x47, 0xee, 0xd0, 0x76, 0x64,
	0x64, 0xef, 0x91, 0xf4, 0x26, 0x08, 0x63, 0x04, 0xed, 0x21, 0xf1, 0x03, 0x8f, 0x10, 0x4b, 0x06,
	0x5e, 0xad, 0x13, 0x6f, 0x82, 0x0c, 0xdc, 0x81, 0xc6, 0xc4, 0x76, 0x86, 0xd2, 0xff, 0xd6, 0x7d,
	0x90, 0xde, 0x04, 0x7d, 0xef, 0xe2, 0x7d, 0xd8, 0x35, 0xc7, 0x56, 0x60, 0xba, 0xe3, 0xb1, 0xeb,
	0x04, 0xc4, 0xb1, 0xd0, 0xfd, 0x7d, 0xfd, 0xf8, 0x87, 0x02, 0xf0, 0xf0, 0x98, 0x44, 0x57, 0x4a,
	0xbc, 0xe9, 0xc8, 0x0f, 0xdc, 0xb3, 0x72, 0xf6, 0x4a, 0xfa, 0xf6, 0x98, 0xb8, 0x53, 0x1f, 0x29,
	0x78, 0x0f, 0x3a, 0x15, 0x9b, 0x3a, 0x83, 0xa9, 0x7f, 0x8a, 0x54, 0x7c, 0x00, 0x78, 0x85, 0xce,
	0x1c, 0xf7, 0x83, 0x13, 0x98, 0x63, 0x0b, 0xd5, 0x1e, 0x5d, 0xb7, 0x9d, 0xf3, 0xc1, 0xc8, 0xb6,
	0x50, 0x1d, 0xff, 0x0f, 0xff, 0xae, 0x98, 0x4f, 0xa8, 0x33, 0x18, 0x05, 0x84, 0x52, 0x97, 0xa2,
	0xed, 0xe3, 0xb7, 0xa0, 0x95, 0x6f, 0x44, 0x5c, 0x1c, 0x12, 0xc7, 0x22, 0x74, 0x59, 0x10, 0x6d,
	0x89, 0xbe, 0x15, 0x7b, 0x47, 0xc6, 0x83, 0x11, 0x41, 0x0a, 0xfe, 0x07, 0x5a, 0x15, 0x92, 0x40,
	0x3d, 0xa9, 0x7f, 0x54, 0xe7, 0x17, 0x17, 0x9a, 0xdc, 0xd6, 0xeb, 0xdf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x21, 0x10, 0xa3, 0x97, 0x6d, 0x04, 0x00, 0x00,
}
