// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

/*
Package common is a generated protocol buffer package.

It is generated from these files:
	common.proto

It has these top-level messages:
	RspHeader
	UserInfo
	Location
	NetworkConfig
	AppConfig
	LoginRsp
	C2SGetSeedReq
	S2CGetSeedRsp
	C2SLoginReq
	S2CLoginRsp
	S2CKickNotify
*/
package common

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// / commands
// / S -> C : even
// / C -> S : odd
type Cmd int32

const (
	Cmd_RESERVED Cmd = 0
	// / Common Commands, handle by agent
	Cmd_HEART_BEAT_REQ Cmd = 1
	Cmd_HEART_BEAT_RSP Cmd = 2
	Cmd_KICK_NOTIFY    Cmd = 4
	Cmd_GET_SEED_REQ   Cmd = 17
	Cmd_GET_SEED_RSP   Cmd = 18
	Cmd_LOGIN_REQ      Cmd = 33
	Cmd_LOGIN_RSP      Cmd = 34
	Cmd_LOGOUT_REQ     Cmd = 51
	Cmd_LOGOUT_RSP     Cmd = 52
	Cmd_OFFLINE_REQ    Cmd = 135
	Cmd_PING_REQ       Cmd = 4097
	Cmd_PING_RSP       Cmd = 4098
	// / Hall Commands, handle by agent
	Cmd_ROOM_CONFIG_REQ Cmd = 8193
	Cmd_ROOM_CONFIG_RSP Cmd = 8194
	Cmd_CREATE_ROOM_REQ Cmd = 8195
	Cmd_CREATE_ROOM_RSP Cmd = 8196
	Cmd_ENTER_ROOM_REQ  Cmd = 8197
	Cmd_ENTER_ROOM_RSP  Cmd = 8198
	Cmd_CMD_COMMON_END  Cmd = 65536
	// / Room Commands, handle by game
	Cmd_EXIT_ROOM_REQ Cmd = 65543
	Cmd_EXIT_ROOM_RSP Cmd = 65544
)

var Cmd_name = map[int32]string{
	0:     "RESERVED",
	1:     "HEART_BEAT_REQ",
	2:     "HEART_BEAT_RSP",
	4:     "KICK_NOTIFY",
	17:    "GET_SEED_REQ",
	18:    "GET_SEED_RSP",
	33:    "LOGIN_REQ",
	34:    "LOGIN_RSP",
	51:    "LOGOUT_REQ",
	52:    "LOGOUT_RSP",
	135:   "OFFLINE_REQ",
	4097:  "PING_REQ",
	4098:  "PING_RSP",
	8193:  "ROOM_CONFIG_REQ",
	8194:  "ROOM_CONFIG_RSP",
	8195:  "CREATE_ROOM_REQ",
	8196:  "CREATE_ROOM_RSP",
	8197:  "ENTER_ROOM_REQ",
	8198:  "ENTER_ROOM_RSP",
	65536: "CMD_COMMON_END",
	65543: "EXIT_ROOM_REQ",
	65544: "EXIT_ROOM_RSP",
}
var Cmd_value = map[string]int32{
	"RESERVED":        0,
	"HEART_BEAT_REQ":  1,
	"HEART_BEAT_RSP":  2,
	"KICK_NOTIFY":     4,
	"GET_SEED_REQ":    17,
	"GET_SEED_RSP":    18,
	"LOGIN_REQ":       33,
	"LOGIN_RSP":       34,
	"LOGOUT_REQ":      51,
	"LOGOUT_RSP":      52,
	"OFFLINE_REQ":     135,
	"PING_REQ":        4097,
	"PING_RSP":        4098,
	"ROOM_CONFIG_REQ": 8193,
	"ROOM_CONFIG_RSP": 8194,
	"CREATE_ROOM_REQ": 8195,
	"CREATE_ROOM_RSP": 8196,
	"ENTER_ROOM_REQ":  8197,
	"ENTER_ROOM_RSP":  8198,
	"CMD_COMMON_END":  65536,
	"EXIT_ROOM_REQ":   65543,
	"EXIT_ROOM_RSP":   65544,
}

func (x Cmd) String() string {
	return proto.EnumName(Cmd_name, int32(x))
}
func (Cmd) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ResultCode int32

const (
	ResultCode_RESULT_OK             ResultCode = 0
	ResultCode_RESULT_TIMEOUT        ResultCode = 1
	ResultCode_RESULT_UNAUTH         ResultCode = 2
	ResultCode_RESULT_UNKNOWN_CMD    ResultCode = 3
	ResultCode_RESULT_INVALID        ResultCode = 4
	ResultCode_RESULT_INTERNAL_ERROR ResultCode = 5
)

var ResultCode_name = map[int32]string{
	0: "RESULT_OK",
	1: "RESULT_TIMEOUT",
	2: "RESULT_UNAUTH",
	3: "RESULT_UNKNOWN_CMD",
	4: "RESULT_INVALID",
	5: "RESULT_INTERNAL_ERROR",
}
var ResultCode_value = map[string]int32{
	"RESULT_OK":             0,
	"RESULT_TIMEOUT":        1,
	"RESULT_UNAUTH":         2,
	"RESULT_UNKNOWN_CMD":    3,
	"RESULT_INVALID":        4,
	"RESULT_INTERNAL_ERROR": 5,
}

func (x ResultCode) String() string {
	return proto.EnumName(ResultCode_name, int32(x))
}
func (ResultCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Gender int32

const (
	Gender_GENDER_UNKNOWN Gender = 0
	Gender_GENDER_FEMALE  Gender = 1
	Gender_GENDER_MALE    Gender = 2
)

var Gender_name = map[int32]string{
	0: "GENDER_UNKNOWN",
	1: "GENDER_FEMALE",
	2: "GENDER_MALE",
}
var Gender_value = map[string]int32{
	"GENDER_UNKNOWN": 0,
	"GENDER_FEMALE":  1,
	"GENDER_MALE":    2,
}

func (x Gender) String() string {
	return proto.EnumName(Gender_name, int32(x))
}
func (Gender) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type KickReason int32

const (
	KickReason_KICK_NO_REASON         KickReason = 0
	KickReason_KICK_LOGIN_ELSEWHERE   KickReason = 1
	KickReason_KICK_SESSION_EXPIRED   KickReason = 2
	KickReason_KICK_ILLEGAL_OPERATION KickReason = 3
	KickReason_KICK_BANNED            KickReason = 4
)

var KickReason_name = map[int32]string{
	0: "KICK_NO_REASON",
	1: "KICK_LOGIN_ELSEWHERE",
	2: "KICK_SESSION_EXPIRED",
	3: "KICK_ILLEGAL_OPERATION",
	4: "KICK_BANNED",
}
var KickReason_value = map[string]int32{
	"KICK_NO_REASON":         0,
	"KICK_LOGIN_ELSEWHERE":   1,
	"KICK_SESSION_EXPIRED":   2,
	"KICK_ILLEGAL_OPERATION": 3,
	"KICK_BANNED":            4,
}

func (x KickReason) String() string {
	return proto.EnumName(KickReason_name, int32(x))
}
func (KickReason) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// / Common Response Header
type RspHeader struct {
	Status    int32  `protobuf:"varint,1,opt,name=status" json:"status"`
	Timestamp uint64 `protobuf:"fixed64,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Msg       string `protobuf:"bytes,3,opt,name=msg" json:"msg,omitempty"`
}

func (m *RspHeader) Reset()                    { *m = RspHeader{} }
func (m *RspHeader) String() string            { return proto.CompactTextString(m) }
func (*RspHeader) ProtoMessage()               {}
func (*RspHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RspHeader) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *RspHeader) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *RspHeader) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// / User Information
type UserInfo struct {
	Usn       uint64 `protobuf:"fixed64,1,opt,name=usn" json:"usn,omitempty"`
	Uid       uint64 `protobuf:"varint,2,opt,name=uid" json:"uid"`
	Birthday  uint64 `protobuf:"fixed64,3,opt,name=birthday" json:"birthday,omitempty"`
	Gender    Gender `protobuf:"varint,4,opt,name=gender,enum=proto.common.Gender" json:"gender"`
	Nickname  string `protobuf:"bytes,5,opt,name=nickname" json:"nickname,omitempty"`
	Email     string `protobuf:"bytes,6,opt,name=email" json:"email,omitempty"`
	Avatar    string `protobuf:"bytes,7,opt,name=avatar" json:"avatar,omitempty"`
	Country   string `protobuf:"bytes,8,opt,name=country" json:"country,omitempty"`
	Since     uint64 `protobuf:"fixed64,9,opt,name=since" json:"since,omitempty"`
	LastLogin uint64 `protobuf:"fixed64,10,opt,name=last_login,json=lastLogin" json:"last_login,omitempty"`
}

func (m *UserInfo) Reset()                    { *m = UserInfo{} }
func (m *UserInfo) String() string            { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()               {}
func (*UserInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserInfo) GetUsn() uint64 {
	if m != nil {
		return m.Usn
	}
	return 0
}

func (m *UserInfo) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UserInfo) GetBirthday() uint64 {
	if m != nil {
		return m.Birthday
	}
	return 0
}

func (m *UserInfo) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_GENDER_UNKNOWN
}

func (m *UserInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserInfo) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *UserInfo) GetSince() uint64 {
	if m != nil {
		return m.Since
	}
	return 0
}

func (m *UserInfo) GetLastLogin() uint64 {
	if m != nil {
		return m.LastLogin
	}
	return 0
}

type Location struct {
	Longitude string `protobuf:"bytes,1,opt,name=longitude" json:"longitude,omitempty"`
	Latitude  string `protobuf:"bytes,2,opt,name=latitude" json:"latitude,omitempty"`
	Address   string `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
}

func (m *Location) Reset()                    { *m = Location{} }
func (m *Location) String() string            { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()               {}
func (*Location) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Location) GetLongitude() string {
	if m != nil {
		return m.Longitude
	}
	return ""
}

func (m *Location) GetLatitude() string {
	if m != nil {
		return m.Latitude
	}
	return ""
}

func (m *Location) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// / Network Configuration Item
// / tell client where to connect
type NetworkConfig struct {
	Id   int32  `protobuf:"varint,1,opt,name=id" json:"id"`
	Desc string `protobuf:"bytes,2,opt,name=desc" json:"desc,omitempty"`
	Ip   string `protobuf:"bytes,3,opt,name=ip" json:"ip,omitempty"`
	Port int32  `protobuf:"varint,4,opt,name=port" json:"port"`
}

func (m *NetworkConfig) Reset()                    { *m = NetworkConfig{} }
func (m *NetworkConfig) String() string            { return proto.CompactTextString(m) }
func (*NetworkConfig) ProtoMessage()               {}
func (*NetworkConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *NetworkConfig) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NetworkConfig) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *NetworkConfig) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *NetworkConfig) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

// / Client Application Configuration
// / tell client how to behave
type AppConfig struct {
	NetworkCfg []*NetworkConfig `protobuf:"bytes,1,rep,name=network_cfg,json=networkCfg" json:"network_cfg,omitempty"`
}

func (m *AppConfig) Reset()                    { *m = AppConfig{} }
func (m *AppConfig) String() string            { return proto.CompactTextString(m) }
func (*AppConfig) ProtoMessage()               {}
func (*AppConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AppConfig) GetNetworkCfg() []*NetworkConfig {
	if m != nil {
		return m.NetworkCfg
	}
	return nil
}

// / HTTP Login Response
type LoginRsp struct {
	Header   *RspHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Token    string     `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	Config   *AppConfig `protobuf:"bytes,3,opt,name=config" json:"config,omitempty"`
	UserInfo *UserInfo  `protobuf:"bytes,4,opt,name=user_info,json=userInfo" json:"user_info,omitempty"`
}

func (m *LoginRsp) Reset()                    { *m = LoginRsp{} }
func (m *LoginRsp) String() string            { return proto.CompactTextString(m) }
func (*LoginRsp) ProtoMessage()               {}
func (*LoginRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *LoginRsp) GetHeader() *RspHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *LoginRsp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginRsp) GetConfig() *AppConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *LoginRsp) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

// / Cryption Key Request
// / C->S
type C2SGetSeedReq struct {
	SendSeed []byte `protobuf:"bytes,1,opt,name=send_seed,json=sendSeed,proto3" json:"send_seed,omitempty"`
	RecvSeed []byte `protobuf:"bytes,2,opt,name=recv_seed,json=recvSeed,proto3" json:"recv_seed,omitempty"`
}

func (m *C2SGetSeedReq) Reset()                    { *m = C2SGetSeedReq{} }
func (m *C2SGetSeedReq) String() string            { return proto.CompactTextString(m) }
func (*C2SGetSeedReq) ProtoMessage()               {}
func (*C2SGetSeedReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *C2SGetSeedReq) GetSendSeed() []byte {
	if m != nil {
		return m.SendSeed
	}
	return nil
}

func (m *C2SGetSeedReq) GetRecvSeed() []byte {
	if m != nil {
		return m.RecvSeed
	}
	return nil
}

// / Cryption Key Response
// / S->C
type S2CGetSeedRsp struct {
	Header   *RspHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	SendSeed []byte     `protobuf:"bytes,2,opt,name=send_seed,json=sendSeed,proto3" json:"send_seed,omitempty"`
	RecvSeed []byte     `protobuf:"bytes,3,opt,name=recv_seed,json=recvSeed,proto3" json:"recv_seed,omitempty"`
}

func (m *S2CGetSeedRsp) Reset()                    { *m = S2CGetSeedRsp{} }
func (m *S2CGetSeedRsp) String() string            { return proto.CompactTextString(m) }
func (*S2CGetSeedRsp) ProtoMessage()               {}
func (*S2CGetSeedRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *S2CGetSeedRsp) GetHeader() *RspHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *S2CGetSeedRsp) GetSendSeed() []byte {
	if m != nil {
		return m.SendSeed
	}
	return nil
}

func (m *S2CGetSeedRsp) GetRecvSeed() []byte {
	if m != nil {
		return m.RecvSeed
	}
	return nil
}

// / Socket Login Request
type C2SLoginReq struct {
	Timestamp uint64 `protobuf:"fixed64,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Usn       uint64 `protobuf:"fixed64,2,opt,name=usn" json:"usn,omitempty"`
	Token     string `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
}

func (m *C2SLoginReq) Reset()                    { *m = C2SLoginReq{} }
func (m *C2SLoginReq) String() string            { return proto.CompactTextString(m) }
func (*C2SLoginReq) ProtoMessage()               {}
func (*C2SLoginReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *C2SLoginReq) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *C2SLoginReq) GetUsn() uint64 {
	if m != nil {
		return m.Usn
	}
	return 0
}

func (m *C2SLoginReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type S2CLoginRsp struct {
	Header *RspHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
}

func (m *S2CLoginRsp) Reset()                    { *m = S2CLoginRsp{} }
func (m *S2CLoginRsp) String() string            { return proto.CompactTextString(m) }
func (*S2CLoginRsp) ProtoMessage()               {}
func (*S2CLoginRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *S2CLoginRsp) GetHeader() *RspHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type S2CKickNotify struct {
	Timestamp uint64     `protobuf:"fixed64,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Reason    KickReason `protobuf:"varint,2,opt,name=reason,enum=proto.common.KickReason" json:"reason"`
	Msg       string     `protobuf:"bytes,3,opt,name=msg" json:"msg,omitempty"`
}

func (m *S2CKickNotify) Reset()                    { *m = S2CKickNotify{} }
func (m *S2CKickNotify) String() string            { return proto.CompactTextString(m) }
func (*S2CKickNotify) ProtoMessage()               {}
func (*S2CKickNotify) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *S2CKickNotify) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *S2CKickNotify) GetReason() KickReason {
	if m != nil {
		return m.Reason
	}
	return KickReason_KICK_NO_REASON
}

func (m *S2CKickNotify) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*RspHeader)(nil), "proto.common.RspHeader")
	proto.RegisterType((*UserInfo)(nil), "proto.common.UserInfo")
	proto.RegisterType((*Location)(nil), "proto.common.Location")
	proto.RegisterType((*NetworkConfig)(nil), "proto.common.NetworkConfig")
	proto.RegisterType((*AppConfig)(nil), "proto.common.AppConfig")
	proto.RegisterType((*LoginRsp)(nil), "proto.common.LoginRsp")
	proto.RegisterType((*C2SGetSeedReq)(nil), "proto.common.C2SGetSeedReq")
	proto.RegisterType((*S2CGetSeedRsp)(nil), "proto.common.S2CGetSeedRsp")
	proto.RegisterType((*C2SLoginReq)(nil), "proto.common.C2SLoginReq")
	proto.RegisterType((*S2CLoginRsp)(nil), "proto.common.S2CLoginRsp")
	proto.RegisterType((*S2CKickNotify)(nil), "proto.common.S2CKickNotify")
	proto.RegisterEnum("proto.common.Cmd", Cmd_name, Cmd_value)
	proto.RegisterEnum("proto.common.ResultCode", ResultCode_name, ResultCode_value)
	proto.RegisterEnum("proto.common.Gender", Gender_name, Gender_value)
	proto.RegisterEnum("proto.common.KickReason", KickReason_name, KickReason_value)
}

func init() { proto.RegisterFile("common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1068 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x5d, 0x8f, 0xda, 0x46,
	0x14, 0x8d, 0x0d, 0x4b, 0xe0, 0xb2, 0x90, 0xc9, 0x64, 0xbb, 0x75, 0x93, 0x56, 0xa2, 0x3c, 0xa1,
	0x55, 0xbb, 0x54, 0xa4, 0x8f, 0x55, 0x15, 0xc7, 0xcc, 0xb2, 0xd6, 0x1a, 0x9b, 0xce, 0x98, 0x24,
	0xed, 0x43, 0x2d, 0x2f, 0x1e, 0x88, 0xb5, 0x60, 0x13, 0xdb, 0xa4, 0xda, 0x3e, 0x6d, 0xfa, 0x95,
	0xf6, 0xb1, 0xff, 0xa0, 0xff, 0xa2, 0x7f, 0xaf, 0x9a, 0xb1, 0x81, 0x25, 0x54, 0xad, 0x94, 0x27,
	0xe6, 0x9c, 0x73, 0xe7, 0xcc, 0x9d, 0x3b, 0xf7, 0x62, 0x38, 0x9c, 0xc4, 0x8b, 0x45, 0x1c, 0x9d,
	0x2e, 0x93, 0x38, 0x8b, 0xf1, 0xa1, 0xfc, 0x39, 0xcd, 0xb9, 0x36, 0x83, 0x1a, 0x4d, 0x97, 0xe7,
	0xdc, 0x0f, 0x78, 0x82, 0x8f, 0xa1, 0x92, 0x66, 0x7e, 0xb6, 0x4a, 0x35, 0xa5, 0xa5, 0x74, 0x0e,
	0x68, 0x81, 0xf0, 0xc7, 0x50, 0xcb, 0xc2, 0x05, 0x4f, 0x33, 0x7f, 0xb1, 0xd4, 0xd4, 0x96, 0xd2,
	0xa9, 0xd0, 0x2d, 0x81, 0x11, 0x94, 0x16, 0xe9, 0x4c, 0x2b, 0xb5, 0x94, 0x4e, 0x8d, 0x8a, 0x65,
	0xfb, 0x4f, 0x15, 0xaa, 0xe3, 0x94, 0x27, 0x66, 0x34, 0x8d, 0x85, 0xbc, 0x4a, 0x23, 0xe9, 0x58,
	0xa1, 0x62, 0x29, 0x99, 0x30, 0x90, 0x46, 0x65, 0x2a, 0x96, 0xf8, 0x21, 0x54, 0x2f, 0xc3, 0x24,
	0x7b, 0x19, 0xf8, 0xd7, 0xd2, 0xa7, 0x42, 0x37, 0x18, 0x7f, 0x06, 0x95, 0x19, 0x8f, 0x02, 0x9e,
	0x68, 0xe5, 0x96, 0xd2, 0x69, 0xf6, 0x8e, 0x4e, 0x6f, 0x5f, 0xe0, 0x74, 0x20, 0x35, 0x5a, 0xc4,
	0x08, 0xa7, 0x28, 0x9c, 0x5c, 0x45, 0xfe, 0x82, 0x6b, 0x07, 0x32, 0xa3, 0x0d, 0xc6, 0x47, 0x70,
	0xc0, 0x17, 0x7e, 0x38, 0xd7, 0x2a, 0x52, 0xc8, 0x81, 0xb8, 0xb4, 0xff, 0xda, 0xcf, 0xfc, 0x44,
	0xbb, 0x2b, 0xe9, 0x02, 0x61, 0x0d, 0xee, 0x4e, 0xe2, 0x55, 0x94, 0x25, 0xd7, 0x5a, 0x55, 0x0a,
	0x6b, 0x28, 0x7c, 0xd2, 0x30, 0x9a, 0x70, 0xad, 0x26, 0x53, 0xcd, 0x01, 0xfe, 0x04, 0x60, 0xee,
	0xa7, 0x99, 0x37, 0x8f, 0x67, 0x61, 0xa4, 0x41, 0x5e, 0x25, 0xc1, 0x58, 0x82, 0x68, 0x7f, 0x0f,
	0x55, 0x2b, 0x9e, 0xf8, 0x59, 0x18, 0x47, 0xa2, 0x9e, 0xf3, 0x38, 0x9a, 0x85, 0xd9, 0x2a, 0xe0,
	0xb2, 0x30, 0x35, 0xba, 0x25, 0xc4, 0x15, 0xe6, 0x7e, 0x96, 0x8b, 0x6a, 0x7e, 0x85, 0x35, 0x16,
	0x49, 0xf9, 0x41, 0x90, 0xf0, 0x34, 0x2d, 0xea, 0xbd, 0x86, 0xed, 0xe7, 0xd0, 0xb0, 0x79, 0xf6,
	0x43, 0x9c, 0x5c, 0x19, 0x71, 0x34, 0x0d, 0x67, 0xb8, 0x09, 0x6a, 0x18, 0x14, 0x0f, 0xa9, 0x86,
	0x01, 0xc6, 0x50, 0x0e, 0x78, 0x3a, 0x29, 0x2c, 0xe5, 0x5a, 0xc6, 0x2c, 0x0b, 0x27, 0x35, 0x5c,
	0x8a, 0x98, 0x65, 0x9c, 0x64, 0xb2, 0xd2, 0x07, 0x54, 0xae, 0xdb, 0x26, 0xd4, 0xf4, 0xe5, 0xb2,
	0x30, 0xfd, 0x0a, 0xea, 0x51, 0x7e, 0x8a, 0x37, 0x99, 0xce, 0x34, 0xa5, 0x55, 0xea, 0xd4, 0x7b,
	0x8f, 0x76, 0x5f, 0x64, 0x27, 0x0d, 0x0a, 0x45, 0xbc, 0x31, 0x9d, 0xb5, 0xff, 0x56, 0x44, 0x11,
	0x66, 0x61, 0x44, 0xd3, 0x25, 0xee, 0x42, 0xe5, 0xa5, 0x6c, 0x3b, 0x99, 0x63, 0xbd, 0xf7, 0xe1,
	0xae, 0xcb, 0xa6, 0x2b, 0x69, 0x11, 0x26, 0xca, 0x9e, 0xc5, 0x57, 0x3c, 0x2a, 0x6e, 0x90, 0x03,
	0x61, 0x33, 0x91, 0x27, 0xc9, 0x6b, 0xec, 0xd9, 0x6c, 0x52, 0xa7, 0x45, 0x18, 0x7e, 0x0c, 0xb5,
	0x55, 0xca, 0x13, 0x2f, 0x8c, 0xa6, 0xb1, 0xbc, 0x68, 0xbd, 0x77, 0xbc, 0xbb, 0x67, 0xdd, 0xba,
	0xb4, 0xba, 0x2a, 0x56, 0x6d, 0x13, 0x1a, 0x46, 0x8f, 0x0d, 0x78, 0xc6, 0x38, 0x0f, 0x28, 0x7f,
	0x85, 0x1f, 0x41, 0x2d, 0xe5, 0x51, 0xe0, 0xa5, 0x9c, 0xe7, 0x45, 0x3e, 0xa4, 0x55, 0x41, 0x08,
	0x5d, 0x88, 0x09, 0x9f, 0xbc, 0xce, 0x45, 0x35, 0x17, 0x05, 0x21, 0xc4, 0xf6, 0x8f, 0xd0, 0x60,
	0x3d, 0x63, 0x6d, 0xf5, 0x3e, 0x85, 0xd8, 0x39, 0x5b, 0xfd, 0xaf, 0xb3, 0x4b, 0xef, 0x9c, 0xcd,
	0xa0, 0x6e, 0xf4, 0x58, 0xfe, 0x04, 0xfc, 0xd5, 0xee, 0x5c, 0x2b, 0xff, 0x32, 0xd7, 0x62, 0x70,
	0xd5, 0xed, 0xe0, 0x6e, 0x5e, 0xa0, 0x74, 0xeb, 0x05, 0xda, 0x5f, 0x43, 0x9d, 0xf5, 0x8c, 0xf7,
	0x7e, 0xd7, 0xf6, 0x2b, 0x59, 0x90, 0x8b, 0x70, 0x72, 0x65, 0xc7, 0x59, 0x38, 0xbd, 0xfe, 0x9f,
	0xb4, 0xbe, 0x80, 0x4a, 0xc2, 0xfd, 0x34, 0xce, 0x33, 0x6b, 0xf6, 0xb4, 0x5d, 0x7f, 0xe1, 0x43,
	0xa5, 0x4e, 0x8b, 0xb8, 0xfd, 0x3f, 0xa8, 0x93, 0xbf, 0x4a, 0x50, 0x32, 0x16, 0x01, 0x3e, 0x84,
	0x2a, 0x25, 0x8c, 0xd0, 0x67, 0xa4, 0x8f, 0xee, 0x60, 0x0c, 0xcd, 0x73, 0xa2, 0x53, 0xd7, 0x7b,
	0x4a, 0x74, 0xd7, 0xa3, 0xe4, 0x1b, 0xa4, 0xbc, 0xcb, 0xb1, 0x11, 0x52, 0xf1, 0x3d, 0xa8, 0x5f,
	0x98, 0xc6, 0x85, 0x67, 0x3b, 0xae, 0x79, 0xf6, 0x2d, 0x2a, 0x63, 0x04, 0x87, 0x03, 0xe2, 0x7a,
	0x8c, 0x90, 0xbe, 0xdc, 0x76, 0x7f, 0x97, 0x61, 0x23, 0x84, 0x71, 0x03, 0x6a, 0x96, 0x33, 0x30,
	0x6d, 0x19, 0xf0, 0xe9, 0x2d, 0xc8, 0x46, 0xa8, 0x8d, 0x9b, 0x00, 0x96, 0x33, 0x70, 0xc6, 0xf9,
	0xb1, 0x8f, 0x6f, 0x63, 0x36, 0x42, 0x5f, 0x62, 0x04, 0x75, 0xe7, 0xec, 0xcc, 0x32, 0x6d, 0x22,
	0x03, 0xde, 0x2a, 0xb8, 0x01, 0xd5, 0x91, 0x69, 0x0f, 0x24, 0x7c, 0xd3, 0xda, 0x42, 0x36, 0x42,
	0x3f, 0xb5, 0xf0, 0x11, 0xdc, 0xa3, 0x8e, 0x33, 0xf4, 0x0c, 0xc7, 0x3e, 0x33, 0x8b, 0xa0, 0x27,
	0x7b, 0xac, 0x88, 0x95, 0xac, 0x41, 0x89, 0xee, 0x12, 0x4f, 0x8a, 0x22, 0xf6, 0xe7, 0x7d, 0x96,
	0x8d, 0xd0, 0x2f, 0x4f, 0xf0, 0x03, 0x68, 0x12, 0xdb, 0x25, 0x74, 0x1b, 0xfa, 0xeb, 0x1e, 0xc9,
	0x46, 0xe8, 0x37, 0xb1, 0xbf, 0x69, 0x0c, 0xfb, 0x9e, 0xe1, 0x0c, 0x87, 0x8e, 0xed, 0x11, 0xbb,
	0x8f, 0x6e, 0x6e, 0xca, 0xf8, 0x01, 0x34, 0xc8, 0x0b, 0xd3, 0xdd, 0x6e, 0x7f, 0xbb, 0x47, 0xb2,
	0x11, 0xfa, 0xfd, 0xa6, 0x7c, 0xf2, 0x87, 0x02, 0x40, 0x79, 0xba, 0x9a, 0x67, 0x46, 0x1c, 0x70,
	0x51, 0x2f, 0x4a, 0xd8, 0xd8, 0x72, 0x3d, 0xe7, 0x22, 0x7f, 0xaa, 0x02, 0xba, 0xe6, 0x90, 0x38,
	0x63, 0x17, 0x29, 0xf8, 0x3e, 0x34, 0x0a, 0x6e, 0x6c, 0xeb, 0x63, 0xf7, 0x1c, 0xa9, 0xf8, 0x18,
	0xf0, 0x86, 0xba, 0xb0, 0x9d, 0xe7, 0xb6, 0x67, 0x0c, 0xfb, 0xa8, 0x74, 0x6b, 0xbb, 0x69, 0x3f,
	0xd3, 0x2d, 0xb3, 0x8f, 0xca, 0xf8, 0x23, 0xf8, 0x60, 0xc3, 0xb9, 0x84, 0xda, 0xba, 0xe5, 0x11,
	0x4a, 0x1d, 0x8a, 0x0e, 0x4e, 0x9e, 0x40, 0x25, 0xff, 0xcc, 0x88, 0x8d, 0x03, 0x62, 0xf7, 0x09,
	0x5d, 0x1b, 0xa2, 0x3b, 0xe2, 0xdc, 0x82, 0x3b, 0x23, 0x43, 0xdd, 0x22, 0x48, 0x11, 0x1d, 0x52,
	0x50, 0x92, 0x50, 0x4f, 0xde, 0x28, 0x00, 0xdb, 0xce, 0x14, 0x36, 0x45, 0x07, 0x79, 0x94, 0xe8,
	0xcc, 0x11, 0x36, 0x1a, 0x1c, 0x49, 0x2e, 0x6f, 0x0b, 0x62, 0x31, 0xf2, 0xfc, 0x9c, 0x50, 0xe1,
	0xb6, 0x56, 0x18, 0x61, 0xcc, 0x14, 0xc5, 0x7c, 0x31, 0x32, 0x29, 0xe9, 0x23, 0x15, 0x3f, 0x84,
	0x63, 0xa9, 0x98, 0x96, 0x45, 0x06, 0xba, 0xe5, 0x39, 0x23, 0x42, 0x75, 0xd7, 0x74, 0x6c, 0x54,
	0xda, 0x74, 0xe9, 0x53, 0xdd, 0xb6, 0x49, 0x1f, 0x95, 0x9f, 0x9e, 0x7c, 0xd7, 0x99, 0x85, 0xd9,
	0xcb, 0xd5, 0xa5, 0x18, 0x95, 0xee, 0xc2, 0x4f, 0x33, 0x9e, 0x7c, 0x3e, 0xeb, 0xc6, 0x8b, 0x59,
	0xdc, 0x95, 0x23, 0xd4, 0x5d, 0x5e, 0x76, 0xf3, 0x29, 0xba, 0xac, 0x48, 0xe2, 0xf1, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xc8, 0x91, 0x05, 0x9a, 0x3b, 0x08, 0x00, 0x00,
}
