// Code generated by protoc-gen-go. DO NOT EDIT.
// source: room.proto

/*
Package room is a generated protocol buffer package.

It is generated from these files:
	room.proto

It has these top-level messages:
	C2SEnterRoomReq
	S2CEnterRoomRsp
	C2SCreateRoomReq
*/
package room

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import proto_common "github.com/master-g/omgo/proto/pb/common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RoomType int32

const (
	RoomType_ROOM_NORMAL RoomType = 0
	RoomType_ROOM_BOX    RoomType = 1
)

var RoomType_name = map[int32]string{
	0: "ROOM_NORMAL",
	1: "ROOM_BOX",
}
var RoomType_value = map[string]int32{
	"ROOM_NORMAL": 0,
	"ROOM_BOX":    1,
}

func (x RoomType) String() string {
	return proto.EnumName(RoomType_name, int32(x))
}
func (RoomType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type C2SEnterRoomReq struct {
	RoomType RoomType `protobuf:"varint,1,opt,name=room_type,json=roomType,enum=proto.room.RoomType" json:"room_type"`
}

func (m *C2SEnterRoomReq) Reset()                    { *m = C2SEnterRoomReq{} }
func (m *C2SEnterRoomReq) String() string            { return proto.CompactTextString(m) }
func (*C2SEnterRoomReq) ProtoMessage()               {}
func (*C2SEnterRoomReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *C2SEnterRoomReq) GetRoomType() RoomType {
	if m != nil {
		return m.RoomType
	}
	return RoomType_ROOM_NORMAL
}

type S2CEnterRoomRsp struct {
	Header *proto_common.RspHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
}

func (m *S2CEnterRoomRsp) Reset()                    { *m = S2CEnterRoomRsp{} }
func (m *S2CEnterRoomRsp) String() string            { return proto.CompactTextString(m) }
func (*S2CEnterRoomRsp) ProtoMessage()               {}
func (*S2CEnterRoomRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *S2CEnterRoomRsp) GetHeader() *proto_common.RspHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type C2SCreateRoomReq struct {
	RoomType  RoomType `protobuf:"varint,1,opt,name=room_type,json=roomType,enum=proto.room.RoomType" json:"room_type"`
	RoomCards int32    `protobuf:"varint,2,opt,name=room_cards,json=roomCards" json:"room_cards"`
}

func (m *C2SCreateRoomReq) Reset()                    { *m = C2SCreateRoomReq{} }
func (m *C2SCreateRoomReq) String() string            { return proto.CompactTextString(m) }
func (*C2SCreateRoomReq) ProtoMessage()               {}
func (*C2SCreateRoomReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *C2SCreateRoomReq) GetRoomType() RoomType {
	if m != nil {
		return m.RoomType
	}
	return RoomType_ROOM_NORMAL
}

func (m *C2SCreateRoomReq) GetRoomCards() int32 {
	if m != nil {
		return m.RoomCards
	}
	return 0
}

func init() {
	proto.RegisterType((*C2SEnterRoomReq)(nil), "proto.room.C2SEnterRoomReq")
	proto.RegisterType((*S2CEnterRoomRsp)(nil), "proto.room.S2CEnterRoomRsp")
	proto.RegisterType((*C2SCreateRoomReq)(nil), "proto.room.C2SCreateRoomReq")
	proto.RegisterEnum("proto.room.RoomType", RoomType_name, RoomType_value)
}

func init() { proto.RegisterFile("room.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x8f, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xad, 0xe0, 0x98, 0x6f, 0xc3, 0x96, 0x20, 0x38, 0x04, 0x61, 0xf4, 0x20, 0x55, 0xb0,
	0xc1, 0xf8, 0x17, 0xd8, 0x28, 0x78, 0x70, 0x16, 0x52, 0x0f, 0xe2, 0xa5, 0xb4, 0xeb, 0xa3, 0xf3,
	0x90, 0xbd, 0x98, 0xc6, 0xc3, 0xfe, 0x7b, 0x49, 0x56, 0xd9, 0xdd, 0x53, 0x92, 0xef, 0xfb, 0xf2,
	0x7b, 0xdf, 0x03, 0xb0, 0x44, 0x3a, 0x37, 0x96, 0x1c, 0x31, 0x08, 0x47, 0xee, 0x95, 0xcb, 0xf9,
	0x9a, 0xb4, 0xa6, 0xed, 0xde, 0x49, 0x9f, 0x20, 0x96, 0xa2, 0x7a, 0xde, 0x3a, 0xb4, 0x8a, 0x48,
	0x2b, 0xfc, 0x66, 0xf7, 0x70, 0xea, 0x83, 0xb5, 0xdb, 0x19, 0x5c, 0x44, 0xcb, 0x28, 0x3b, 0x13,
	0xe7, 0xf9, 0x01, 0x90, 0xfb, 0xdc, 0xfb, 0xce, 0xa0, 0x9a, 0xda, 0xf1, 0x96, 0x16, 0x10, 0x57,
	0x42, 0x1e, 0x28, 0x83, 0x61, 0x1c, 0x26, 0x1b, 0x6c, 0x3a, 0xb4, 0x01, 0x31, 0x13, 0x17, 0x23,
	0x62, 0x9c, 0xae, 0x06, 0xf3, 0x12, 0x6c, 0x35, 0xc6, 0xd2, 0x0e, 0x12, 0x29, 0x2a, 0x69, 0xb1,
	0x71, 0xf8, 0xff, 0x2a, 0xec, 0x6a, 0xbf, 0x78, 0xbd, 0x6e, 0x6c, 0x37, 0x2c, 0x8e, 0x97, 0x51,
	0x76, 0xa2, 0x02, 0x44, 0x7a, 0xe1, 0xf6, 0x06, 0xa6, 0x7f, 0x9f, 0x58, 0x0c, 0x33, 0x55, 0x96,
	0xab, 0xfa, 0xad, 0x54, 0xab, 0xc7, 0xd7, 0xe4, 0x88, 0xcd, 0x61, 0x1a, 0x84, 0xa2, 0xfc, 0x48,
	0xa2, 0x22, 0xfb, 0xbc, 0xee, 0xbf, 0xdc, 0xe6, 0xa7, 0xf5, 0x9d, 0xb9, 0x6e, 0x06, 0x87, 0xf6,
	0xae, 0xe7, 0xa4, 0x7b, 0xe2, 0xa1, 0x03, 0x37, 0x2d, 0xf7, 0xe4, 0x76, 0x12, 0x9e, 0x0f, 0xbf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xfd, 0x0e, 0x2f, 0xc2, 0x73, 0x01, 0x00, 0x00,
}
