// Code generated by protoc-gen-go. DO NOT EDIT.
// source: room.proto

/*
Package room is a generated protocol buffer package.

It is generated from these files:
	room.proto

It has these top-level messages:
	RoomInfo
	C2SEnterRoomReq
	S2CEnterRoomRsp
	C2SCreateRoomReq
*/
package room

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import proto_common "github.com/master-g/omgo/proto/pb/common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RoomType int32

const (
	RoomType_ROOM_RESERVED RoomType = 0
	RoomType_ROOM_NORMAL   RoomType = 1
	RoomType_ROOM_PRIVATE  RoomType = 2
)

var RoomType_name = map[int32]string{
	0: "ROOM_RESERVED",
	1: "ROOM_NORMAL",
	2: "ROOM_PRIVATE",
}
var RoomType_value = map[string]int32{
	"ROOM_RESERVED": 0,
	"ROOM_NORMAL":   1,
	"ROOM_PRIVATE":  2,
}

func (x RoomType) String() string {
	return proto.EnumName(RoomType_name, int32(x))
}
func (RoomType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PlayType int32

const (
	PlayType_PLAY_TYPE_RESERVED PlayType = 0
	PlayType_PLAY_TYPE_RACE     PlayType = 1
	PlayType_PLAY_TYPE_CALL     PlayType = 2
)

var PlayType_name = map[int32]string{
	0: "PLAY_TYPE_RESERVED",
	1: "PLAY_TYPE_RACE",
	2: "PLAY_TYPE_CALL",
}
var PlayType_value = map[string]int32{
	"PLAY_TYPE_RESERVED": 0,
	"PLAY_TYPE_RACE":     1,
	"PLAY_TYPE_CALL":     2,
}

func (x PlayType) String() string {
	return proto.EnumName(PlayType_name, int32(x))
}
func (PlayType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type EnterRoomResult int32

const (
	EnterRoomResult_ENTER_ROOM_OK                  EnterRoomResult = 0
	EnterRoomResult_ENTER_ROOM_INSUFFICIENT_CREDIT EnterRoomResult = 1
	EnterRoomResult_ENTER_ROOM_WRONG_PASSWORD      EnterRoomResult = 2
	EnterRoomResult_ENTER_ROOM_NOT_EXIST           EnterRoomResult = 3
	EnterRoomResult_ENTER_ROOM_FULL                EnterRoomResult = 4
	EnterRoomResult_ENTER_ROOM_FAIL_NO_OBSERVE     EnterRoomResult = 5
)

var EnterRoomResult_name = map[int32]string{
	0: "ENTER_ROOM_OK",
	1: "ENTER_ROOM_INSUFFICIENT_CREDIT",
	2: "ENTER_ROOM_WRONG_PASSWORD",
	3: "ENTER_ROOM_NOT_EXIST",
	4: "ENTER_ROOM_FULL",
	5: "ENTER_ROOM_FAIL_NO_OBSERVE",
}
var EnterRoomResult_value = map[string]int32{
	"ENTER_ROOM_OK":                  0,
	"ENTER_ROOM_INSUFFICIENT_CREDIT": 1,
	"ENTER_ROOM_WRONG_PASSWORD":      2,
	"ENTER_ROOM_NOT_EXIST":           3,
	"ENTER_ROOM_FULL":                4,
	"ENTER_ROOM_FAIL_NO_OBSERVE":     5,
}

func (x EnterRoomResult) String() string {
	return proto.EnumName(EnterRoomResult_name, int32(x))
}
func (EnterRoomResult) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type CreateRoomResult int32

const (
	CreateRoomResult_CREATE_ROOM_OK                CreateRoomResult = 0
	CreateRoomResult_CREATE_ROOM_INVALID_PASSWORD  CreateRoomResult = 1
	CreateRoomResult_CREATE_ROOM_INSUFFICIENT_CARD CreateRoomResult = 2
	CreateRoomResult_CREATE_ROOM_INVALID_PARAM     CreateRoomResult = 3
)

var CreateRoomResult_name = map[int32]string{
	0: "CREATE_ROOM_OK",
	1: "CREATE_ROOM_INVALID_PASSWORD",
	2: "CREATE_ROOM_INSUFFICIENT_CARD",
	3: "CREATE_ROOM_INVALID_PARAM",
}
var CreateRoomResult_value = map[string]int32{
	"CREATE_ROOM_OK":                0,
	"CREATE_ROOM_INVALID_PASSWORD":  1,
	"CREATE_ROOM_INSUFFICIENT_CARD": 2,
	"CREATE_ROOM_INVALID_PARAM":     3,
}

func (x CreateRoomResult) String() string {
	return proto.EnumName(CreateRoomResult_name, int32(x))
}
func (CreateRoomResult) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// desc  : 房间详细信息
type RoomInfo struct {
	Id          uint64   `protobuf:"fixed64,1,opt,name=id" json:"id,omitempty"`
	Owner       uint64   `protobuf:"fixed64,2,opt,name=owner" json:"owner,omitempty"`
	RoomType    RoomType `protobuf:"varint,3,opt,name=room_type,json=roomType,enum=proto.room.RoomType" json:"room_type"`
	PlayType    PlayType `protobuf:"varint,4,opt,name=play_type,json=playType,enum=proto.room.PlayType" json:"play_type"`
	Title       string   `protobuf:"bytes,5,opt,name=title" json:"title,omitempty"`
	Desc        string   `protobuf:"bytes,6,opt,name=desc" json:"desc,omitempty"`
	Since       uint64   `protobuf:"fixed64,7,opt,name=since" json:"since,omitempty"`
	Observable  bool     `protobuf:"varint,8,opt,name=observable" json:"observable"`
	TotalRounds int32    `protobuf:"varint,9,opt,name=total_rounds,json=totalRounds" json:"total_rounds"`
	LeftRounds  int32    `protobuf:"varint,10,opt,name=left_rounds,json=leftRounds" json:"left_rounds"`
	BoomLimit   int32    `protobuf:"varint,11,opt,name=boom_limit,json=boomLimit" json:"boom_limit"`
	Players     []uint64 `protobuf:"fixed64,12,rep,packed,name=players" json:"players,omitempty"`
	Secure      bool     `protobuf:"varint,13,opt,name=secure" json:"secure"`
	Address     string   `protobuf:"bytes,14,opt,name=address" json:"address,omitempty"`
	Longitude   string   `protobuf:"bytes,15,opt,name=longitude" json:"longitude,omitempty"`
	Latitude    string   `protobuf:"bytes,16,opt,name=latitude" json:"latitude,omitempty"`
}

func (m *RoomInfo) Reset()                    { *m = RoomInfo{} }
func (m *RoomInfo) String() string            { return proto.CompactTextString(m) }
func (*RoomInfo) ProtoMessage()               {}
func (*RoomInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RoomInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RoomInfo) GetOwner() uint64 {
	if m != nil {
		return m.Owner
	}
	return 0
}

func (m *RoomInfo) GetRoomType() RoomType {
	if m != nil {
		return m.RoomType
	}
	return RoomType_ROOM_RESERVED
}

func (m *RoomInfo) GetPlayType() PlayType {
	if m != nil {
		return m.PlayType
	}
	return PlayType_PLAY_TYPE_RESERVED
}

func (m *RoomInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *RoomInfo) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *RoomInfo) GetSince() uint64 {
	if m != nil {
		return m.Since
	}
	return 0
}

func (m *RoomInfo) GetObservable() bool {
	if m != nil {
		return m.Observable
	}
	return false
}

func (m *RoomInfo) GetTotalRounds() int32 {
	if m != nil {
		return m.TotalRounds
	}
	return 0
}

func (m *RoomInfo) GetLeftRounds() int32 {
	if m != nil {
		return m.LeftRounds
	}
	return 0
}

func (m *RoomInfo) GetBoomLimit() int32 {
	if m != nil {
		return m.BoomLimit
	}
	return 0
}

func (m *RoomInfo) GetPlayers() []uint64 {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *RoomInfo) GetSecure() bool {
	if m != nil {
		return m.Secure
	}
	return false
}

func (m *RoomInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *RoomInfo) GetLongitude() string {
	if m != nil {
		return m.Longitude
	}
	return ""
}

func (m *RoomInfo) GetLatitude() string {
	if m != nil {
		return m.Latitude
	}
	return ""
}

type C2SEnterRoomReq struct {
	Type     RoomType `protobuf:"varint,1,opt,name=type,enum=proto.room.RoomType" json:"type"`
	RoomId   uint64   `protobuf:"fixed64,2,opt,name=room_id,json=roomId" json:"room_id,omitempty"`
	Password string   `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
}

func (m *C2SEnterRoomReq) Reset()                    { *m = C2SEnterRoomReq{} }
func (m *C2SEnterRoomReq) String() string            { return proto.CompactTextString(m) }
func (*C2SEnterRoomReq) ProtoMessage()               {}
func (*C2SEnterRoomReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *C2SEnterRoomReq) GetType() RoomType {
	if m != nil {
		return m.Type
	}
	return RoomType_ROOM_RESERVED
}

func (m *C2SEnterRoomReq) GetRoomId() uint64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *C2SEnterRoomReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type S2CEnterRoomRsp struct {
	Header *proto_common.RspHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
}

func (m *S2CEnterRoomRsp) Reset()                    { *m = S2CEnterRoomRsp{} }
func (m *S2CEnterRoomRsp) String() string            { return proto.CompactTextString(m) }
func (*S2CEnterRoomRsp) ProtoMessage()               {}
func (*S2CEnterRoomRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *S2CEnterRoomRsp) GetHeader() *proto_common.RspHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type C2SCreateRoomReq struct {
	Type     RoomType `protobuf:"varint,1,opt,name=type,enum=proto.room.RoomType" json:"type"`
	CardNum  int32    `protobuf:"varint,2,opt,name=card_num,json=cardNum" json:"card_num"`
	Password string   `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
}

func (m *C2SCreateRoomReq) Reset()                    { *m = C2SCreateRoomReq{} }
func (m *C2SCreateRoomReq) String() string            { return proto.CompactTextString(m) }
func (*C2SCreateRoomReq) ProtoMessage()               {}
func (*C2SCreateRoomReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *C2SCreateRoomReq) GetType() RoomType {
	if m != nil {
		return m.Type
	}
	return RoomType_ROOM_RESERVED
}

func (m *C2SCreateRoomReq) GetCardNum() int32 {
	if m != nil {
		return m.CardNum
	}
	return 0
}

func (m *C2SCreateRoomReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*RoomInfo)(nil), "proto.room.RoomInfo")
	proto.RegisterType((*C2SEnterRoomReq)(nil), "proto.room.C2SEnterRoomReq")
	proto.RegisterType((*S2CEnterRoomRsp)(nil), "proto.room.S2CEnterRoomRsp")
	proto.RegisterType((*C2SCreateRoomReq)(nil), "proto.room.C2SCreateRoomReq")
	proto.RegisterEnum("proto.room.RoomType", RoomType_name, RoomType_value)
	proto.RegisterEnum("proto.room.PlayType", PlayType_name, PlayType_value)
	proto.RegisterEnum("proto.room.EnterRoomResult", EnterRoomResult_name, EnterRoomResult_value)
	proto.RegisterEnum("proto.room.CreateRoomResult", CreateRoomResult_name, CreateRoomResult_value)
}

func init() { proto.RegisterFile("room.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 730 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xdf, 0x6e, 0xa3, 0x46,
	0x14, 0xc6, 0x17, 0xff, 0xf7, 0xb1, 0xd7, 0x9e, 0x4e, 0xa3, 0x5d, 0x12, 0xad, 0x53, 0xaf, 0x2f,
	0x2a, 0x64, 0xa9, 0xb6, 0xea, 0xbe, 0x40, 0x09, 0x26, 0x2d, 0x2d, 0x01, 0x6b, 0x60, 0xb3, 0xdd,
	0xde, 0x20, 0x6c, 0x66, 0x1d, 0x24, 0x60, 0x28, 0xe0, 0x46, 0x7e, 0x85, 0x3e, 0x50, 0x5f, 0xa7,
	0xaf, 0x52, 0xcd, 0x80, 0x63, 0xa2, 0x56, 0x91, 0xf6, 0xca, 0xf3, 0xfd, 0xce, 0x39, 0x73, 0xbe,
	0xf1, 0x39, 0x00, 0x64, 0x8c, 0xc5, 0x8b, 0x34, 0x63, 0x05, 0xc3, 0x20, 0x7e, 0x16, 0x9c, 0x5c,
	0x0d, 0x77, 0x2c, 0x8e, 0x59, 0x52, 0x46, 0x66, 0xff, 0x34, 0xa1, 0x47, 0x18, 0x8b, 0x8d, 0xe4,
	0x33, 0xc3, 0x23, 0x68, 0x84, 0x81, 0x2c, 0x4d, 0x25, 0xa5, 0x43, 0x1a, 0x61, 0x80, 0x2f, 0xa0,
	0xcd, 0x1e, 0x13, 0x9a, 0xc9, 0x0d, 0x81, 0x4a, 0x81, 0xbf, 0x87, 0x3e, 0xbf, 0xc8, 0x2b, 0x8e,
	0x29, 0x95, 0x9b, 0x53, 0x49, 0x19, 0xad, 0x2e, 0x16, 0xe7, 0x06, 0x0b, 0x7e, 0x9d, 0x7b, 0x4c,
	0x29, 0xe9, 0x65, 0xd5, 0x89, 0x97, 0xa4, 0x91, 0x7f, 0x2c, 0x4b, 0x5a, 0xff, 0x2d, 0xd9, 0x44,
	0xfe, 0xb1, 0x2c, 0x49, 0xab, 0x13, 0xef, 0x5d, 0x84, 0x45, 0x44, 0xe5, 0xf6, 0x54, 0x52, 0xfa,
	0xa4, 0x14, 0x18, 0x43, 0x2b, 0xa0, 0xf9, 0x4e, 0xee, 0x08, 0x28, 0xce, 0x3c, 0x33, 0x0f, 0x93,
	0x1d, 0x95, 0xbb, 0xa5, 0x4b, 0x21, 0xf0, 0x35, 0x00, 0xdb, 0xe6, 0x34, 0xfb, 0xd3, 0xdf, 0x46,
	0x54, 0xee, 0x4d, 0x25, 0xa5, 0x47, 0x6a, 0x04, 0xbf, 0x87, 0x61, 0xc1, 0x0a, 0x3f, 0xf2, 0x32,
	0x76, 0x48, 0x82, 0x5c, 0xee, 0x4f, 0x25, 0xa5, 0x4d, 0x06, 0x82, 0x11, 0x81, 0xf0, 0x37, 0x30,
	0x88, 0xe8, 0xe7, 0xe2, 0x94, 0x01, 0x22, 0x03, 0x38, 0xaa, 0x12, 0x26, 0x00, 0x5b, 0xfe, 0x4f,
	0x44, 0x61, 0x1c, 0x16, 0xf2, 0x40, 0xc4, 0xfb, 0x9c, 0x98, 0x1c, 0x60, 0x19, 0xba, 0xfc, 0x39,
	0x34, 0xcb, 0xe5, 0xe1, 0xb4, 0xa9, 0x74, 0xc8, 0x49, 0xe2, 0x37, 0xd0, 0xc9, 0xe9, 0xee, 0x90,
	0x51, 0xf9, 0xb5, 0x30, 0x56, 0x29, 0x5e, 0xe1, 0x07, 0x41, 0x46, 0xf3, 0x5c, 0x1e, 0x89, 0x17,
	0x9e, 0x24, 0x7e, 0x07, 0xfd, 0x88, 0x25, 0xfb, 0xb0, 0x38, 0x04, 0x54, 0x1e, 0x8b, 0xd8, 0x19,
	0xe0, 0x2b, 0xe8, 0x45, 0x7e, 0x51, 0x06, 0x91, 0x08, 0x3e, 0xe9, 0x59, 0x0a, 0x63, 0x6d, 0xe5,
	0xe8, 0x49, 0x41, 0x33, 0x3e, 0x19, 0x42, 0xff, 0xc0, 0x0a, 0xb4, 0xc4, 0x24, 0xa4, 0x17, 0x86,
	0x27, 0x32, 0xf0, 0x5b, 0xe8, 0x8a, 0x59, 0x87, 0x41, 0xb5, 0x03, 0x1d, 0x2e, 0x8d, 0x80, 0x77,
	0x4c, 0xfd, 0x3c, 0x7f, 0x64, 0x59, 0x20, 0x76, 0xa0, 0x4f, 0x9e, 0xf4, 0xec, 0x06, 0xc6, 0xce,
	0x4a, 0x3b, 0x77, 0xcc, 0x53, 0xbc, 0x84, 0xce, 0x03, 0xf5, 0x03, 0x9a, 0x89, 0x9e, 0x83, 0xd5,
	0xdb, 0xaa, 0x67, 0xb5, 0x8b, 0x24, 0x4f, 0x7f, 0x16, 0x61, 0x52, 0xa5, 0xcd, 0x72, 0x40, 0xda,
	0xca, 0xd1, 0x32, 0xea, 0x17, 0xf4, 0xcb, 0x6d, 0x5f, 0x42, 0x6f, 0xe7, 0x67, 0x81, 0x97, 0x1c,
	0x62, 0xe1, 0xbb, 0x4d, 0xba, 0x5c, 0x5b, 0x87, 0xf8, 0x25, 0xe3, 0xf3, 0x1f, 0xcb, 0x6f, 0x41,
	0xec, 0xdf, 0x57, 0xf0, 0x9a, 0xd8, 0xf6, 0x9d, 0x47, 0x74, 0x47, 0x27, 0xf7, 0xfa, 0x1a, 0xbd,
	0xc2, 0x63, 0x18, 0x08, 0x64, 0xd9, 0xe4, 0x4e, 0x35, 0x91, 0x84, 0x11, 0x0c, 0x05, 0xd8, 0x10,
	0xe3, 0x5e, 0x75, 0x75, 0xd4, 0x98, 0xff, 0x02, 0xbd, 0xd3, 0x2e, 0xe3, 0x37, 0x80, 0x37, 0xa6,
	0xfa, 0xc9, 0x73, 0x3f, 0x6d, 0xf4, 0xfa, 0x35, 0x18, 0x46, 0x35, 0xae, 0x6a, 0x3a, 0x92, 0x9e,
	0x33, 0x4d, 0x35, 0x4d, 0xd4, 0x98, 0xff, 0x2d, 0xc1, 0xb8, 0x36, 0xb6, 0xfc, 0x10, 0x15, 0xdc,
	0x95, 0x6e, 0xb9, 0x3a, 0xf1, 0x44, 0x5f, 0xfb, 0x57, 0xf4, 0x0a, 0xcf, 0xe0, 0xba, 0x86, 0x0c,
	0xcb, 0xf9, 0x70, 0x7b, 0x6b, 0x68, 0x86, 0x6e, 0xb9, 0x9e, 0x46, 0xf4, 0xb5, 0xe1, 0x22, 0x09,
	0x4f, 0xe0, 0xb2, 0x96, 0xf3, 0x91, 0xd8, 0xd6, 0x4f, 0xde, 0x46, 0x75, 0x9c, 0x8f, 0x36, 0x59,
	0xa3, 0x06, 0x96, 0xe1, 0xa2, 0x16, 0xb6, 0x6c, 0xd7, 0xd3, 0x7f, 0x33, 0x1c, 0x17, 0x35, 0xf1,
	0xd7, 0x30, 0xae, 0x45, 0x6e, 0x3f, 0x98, 0x26, 0x6a, 0xe1, 0x6b, 0xb8, 0xaa, 0x43, 0xd5, 0x30,
	0x3d, 0xcb, 0xf6, 0xec, 0x1b, 0xf1, 0x42, 0xd4, 0x9e, 0xff, 0x25, 0x01, 0xaa, 0x4f, 0x4e, 0x38,
	0xc7, 0x30, 0xd2, 0x88, 0xae, 0xba, 0x7a, 0xcd, 0xfa, 0x14, 0xde, 0xd5, 0x99, 0x61, 0xdd, 0xab,
	0xa6, 0xb1, 0x3e, 0x3b, 0x93, 0xf0, 0x7b, 0x98, 0x3c, 0xcf, 0xa8, 0xbf, 0x4e, 0x15, 0xe6, 0x27,
	0x70, 0xf9, 0xff, 0x97, 0x10, 0xf5, 0x0e, 0x35, 0x6f, 0x94, 0xdf, 0xbf, 0xdd, 0x87, 0xc5, 0xc3,
	0x61, 0xcb, 0x77, 0x6d, 0x19, 0xfb, 0x79, 0x41, 0xb3, 0xef, 0xf6, 0x4b, 0x16, 0xef, 0xd9, 0x52,
	0x2c, 0xd0, 0x32, 0xdd, 0x2e, 0xf9, 0x0e, 0x6d, 0x3b, 0x42, 0xfe, 0xf0, 0x6f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x4e, 0x9c, 0x21, 0x41, 0x39, 0x05, 0x00, 0x00,
}
